// lib/core/ai/ai_service.dart
//
// Core abstraction for on-device AI / SLM (Small Language Model) inference.
// Designed for strictly offline, bounded, privacy-preserving dementia care.
//
// Requirements:
// - Must NOT require internet.
// - Must NOT directly control Flutter navigation.
// - Must NOT directly modify medicines, patient records, caregiver settings, or delete data.
// - Qwen output must map to predefined VoiceIntent values.
// - Returns clear notInstalled/unavailable results if weights are missing.
// - Zero fake AI / mocks that pretend Qwen is running.

import '../voice/voice_intent.dart';
import 'ai_context_builder.dart';

/// Operational status of the on-device AI service.
enum AiServiceStatus {
  /// Uninitialized state before model check.
  uninitialized,

  /// Model binary or runtime engine is not installed on this host.
  notInstalled,

  /// Loading model weights into device memory.
  loading,

  /// Model is loaded and ready for bounded local inference.
  ready,

  /// On-device execution failed or crashed during inference.
  inferenceError,

  /// Model is unavailable due to hardware or memory constraints.
  unavailable,
}

/// Structured result of local SLM intent inference.
class AiInferenceResult {
  /// Whether inference succeeded and mapped to an approved intent.
  final bool isSuccess;

  /// Raw text generated by the local SLM.
  final String? rawOutput;

  /// Validated, approved VoiceIntent mapped from model output.
  final VoiceIntent? mappedIntent;

  /// Current status of the AI service.
  final AiServiceStatus status;

  /// Error message or failure rationale.
  final String? errorMessage;

  const AiInferenceResult({
    required this.isSuccess,
    this.rawOutput,
    this.mappedIntent,
    required this.status,
    this.errorMessage,
  });

  /// Factory for when model weights or runtime are not installed on disk.
  factory AiInferenceResult.notInstalled({
    String message =
        'Local Qwen model runtime is not installed on this device.',
  }) {
    return AiInferenceResult(
      isSuccess: false,
      status: AiServiceStatus.notInstalled,
      errorMessage: message,
      mappedIntent: const VoiceIntent(
        type: VoiceIntentType.unknown,
        confidence: 0.0,
      ),
    );
  }

  /// Factory for when the service is temporarily or permanently unavailable.
  factory AiInferenceResult.unavailable({
    String message = 'Local AI service is currently unavailable.',
  }) {
    return AiInferenceResult(
      isSuccess: false,
      status: AiServiceStatus.unavailable,
      errorMessage: message,
      mappedIntent: const VoiceIntent(
        type: VoiceIntentType.unknown,
        confidence: 0.0,
      ),
    );
  }

  /// Factory for successful inference that yielded a validated VoiceIntent.
  factory AiInferenceResult.success({
    required String rawOutput,
    required VoiceIntent mappedIntent,
  }) {
    return AiInferenceResult(
      isSuccess: true,
      rawOutput: rawOutput,
      mappedIntent: mappedIntent,
      status: AiServiceStatus.ready,
    );
  }

  /// Factory for failed inference or validation rejection.
  factory AiInferenceResult.failure({
    required String errorMessage,
    AiServiceStatus status = AiServiceStatus.inferenceError,
    String? rawOutput,
  }) {
    return AiInferenceResult(
      isSuccess: false,
      rawOutput: rawOutput,
      status: status,
      errorMessage: errorMessage,
      mappedIntent: const VoiceIntent(
        type: VoiceIntentType.unknown,
        confidence: 0.0,
      ),
    );
  }
}

/// Abstract contract for local on-device AI inference services.
abstract class AiService {
  /// Current runtime status of the AI engine.
  AiServiceStatus get status;

  /// Whether the AI engine is installed, loaded, and available for offline inference.
  bool get isAvailable;

  /// Initialize model and verify offline asset integrity.
  Future<bool> initialize();

  /// Infer user intent from input prompt within the given bounded context.
  Future<AiInferenceResult> inferIntent({
    required String prompt,
    required AiContext context,
  });

  /// Release native memory and model runtime handles.
  Future<void> dispose();
}
