// lib/services/tts/text_to_speech_service.dart
//
// Asynchronous interface for Text-To-Speech (TTS) audio narration.
// Designed with dementia-safe cadence, replay controls, and strict offline constraints.

import 'tts_models.dart';

abstract class TextToSpeechService {
  /// True if TTS engine is initialized and ready to synthesize speech.
  bool get isReady;

  /// True if speech is actively playing through the speaker.
  bool get isSpeaking;

  /// True if speech synthesis is currently paused.
  bool get isPaused;

  /// The active playback rate (default 0.75x for elderly dementia safety).
  double get currentRate;

  /// The most recent text that was spoken or requested for speech.
  String? get lastSpokenText;

  /// Initializes the local TTS engine.
  Future<void> initialize();

  /// Retrieves all on-device available voices.
  Future<List<TTSVoice>> getAvailableVoices();

  /// Checks whether a given language ('en', 'hi', 'as') is supported on the local device.
  Future<TTSLanguageSupport> checkLanguageSupport(String languageCode);

  /// Sets the speech rate (clamped between 0.5 and 1.0 for dementia friendliness).
  Future<void> setSpeechRate(double rate);

  /// Speaks the provided text using the designated locale ('en', 'hi', 'as').
  ///
  /// SAFETY REQUIREMENTS:
  /// 1. Medication dosage instructions generated by LLMs are strictly rejected.
  /// 2. Sensitive patient data is rejected if isSecuredContext is false.
  /// 3. Zero cloud transmission: speech occurs strictly on-device.
  /// 4. If language is not available (e.g. missing Assamese voice), throws/reports clearly
  ///    without silently translating to English or Hindi.
  Future<bool> speak({
    required String text,
    required String languageCode,
    double pitch = 1.0,
    double? rate,
    bool isSecuredContext = true,
  });

  /// Replays the last spoken phrase at the configured elderly speech rate.
  Future<bool> replay();

  /// Pauses ongoing speech playback where supported.
  Future<void> pause();

  /// Resumes paused speech playback where supported.
  Future<void> resume();

  /// Immediately stops ongoing speech and clears active buffers.
  Future<void> stop();
}
