/**
 * src/reminders/reminderModel.js
 *
 * MindCare NER — Smart Reminder Data Model & Immutable State Transitions
 *
 * This module manages:
 * 1. Creation and strict schema validation of Reminder entities.
 * 2. Pure, immutable state transition helpers for the reminder lifecycle:
 *    - Caregiver creates -> PENDING
 *    - Triggered on patient device -> DELIVERED
 *    - Patient / Caregiver completes -> ACKNOWLEDGED
 *    - Postponed -> SNOOZED (with snoozedUntil calculation)
 *    - Passed window -> MISSED
 * 3. Strict privacy safeguards: Rejects / strips passwords and auth tokens.
 *
 * TODO: When backend synchronization is integrated:
 * - Replace client-side ID generation with server UUID / MongoDB ObjectID
 * - Align ISO timestamp parsing with server timezone handling (UTC)
 */

import {
  REMINDER_TYPES,
  REMINDER_REPEAT,
  REMINDER_STATUS,
  DEFAULT_REMINDER,
  isValidReminderType,
  isValidReminderRepeat,
  isValidReminderStatus,
} from './reminderTypes.js'

/**
 * Disallowed sensitive keys that must NEVER be persisted in reminder data.
 */
const SENSITIVE_FORBIDDEN_KEYS = Object.freeze([
  'password',
  'token',
  'secret',
  'authToken',
  'accessToken',
  'pin',
  'apiKey',
  'privateKey',
  'credentials',
])

/**
 * Generates a collision-resistant unique client-side reminder ID.
 * Format: rem_<timestamp>_<random6>
 *
 * TODO: In production, IDs will be generated by the database/backend
 * (e.g. UUIDv4 or MongoDB ObjectId).
 *
 * @returns {string}
 */
export function generateReminderId() {
  const timestamp = Date.now()
  const randomSuffix = Math.random().toString(36).substring(2, 8)
  return `rem_${timestamp}_${randomSuffix}`
}

/**
 * Validates a reminder payload against the required fields and schema constraints.
 *
 * @param {Object} data
 * @returns {{ isValid: boolean, errors: string[] }}
 */
export function validateReminder(data) {
  const errors = []

  if (!data || typeof data !== 'object') {
    return { isValid: false, errors: ['Reminder payload must be a non-null object.'] }
  }

  // 1. Patient ID
  if (!data.patientId || typeof data.patientId !== 'string' || !data.patientId.trim()) {
    errors.push('patientId is required and must be a non-empty string.')
  }

  // 2. Type
  if (!data.type || !isValidReminderType(data.type)) {
    errors.push(`Invalid type "${data.type}". Must be one of: ${Object.values(REMINDER_TYPES).join(', ')}.`)
  }

  // 3. Title
  if (!data.title || typeof data.title !== 'string' || !data.title.trim()) {
    errors.push('title is required and must be a non-empty string.')
  }

  // 4. Scheduled Time (must be valid ISO string or parseable date string)
  if (!data.scheduledTime) {
    errors.push('scheduledTime is required.')
  } else {
    const parsedDate = new Date(data.scheduledTime)
    if (Number.isNaN(parsedDate.getTime())) {
      errors.push(`scheduledTime "${data.scheduledTime}" is not a valid date string.`)
    }
  }

  // 5. Repeat (optional, defaults to 'none')
  if (data.repeat && !isValidReminderRepeat(data.repeat)) {
    errors.push(`Invalid repeat "${data.repeat}". Must be one of: ${Object.values(REMINDER_REPEAT).join(', ')}.`)
  }

  // 6. Status (optional, defaults to 'pending')
  if (data.status && !isValidReminderStatus(data.status)) {
    errors.push(`Invalid status "${data.status}". Must be one of: ${Object.values(REMINDER_STATUS).join(', ')}.`)
  }

  // 7. Security check: Disallow sensitive credential fields
  for (const forbidden of SENSITIVE_FORBIDDEN_KEYS) {
    if (Object.prototype.hasOwnProperty.call(data, forbidden)) {
      errors.push(`Security violation: Reminders must not store credentials or secrets ("${forbidden}").`)
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}

/**
 * Creates a sanitized, schema-compliant Reminder entity.
 *
 * @param {Object} input
 * @returns {Object} A validated reminder object
 * @throws {Error} if validation fails
 */
export function createReminder(input) {
  const validation = validateReminder(input)
  if (!validation.isValid) {
    throw new Error(`[MindCare Reminders] Validation failed:\n- ${validation.errors.join('\n- ')}`)
  }

  const nowIso = new Date().toISOString()
  const scheduledIso = new Date(input.scheduledTime).toISOString()

  const ackTime = input.acknowledgedTime
    ? new Date(input.acknowledgedTime).toISOString()
    : (input.acknowledgedAt ? new Date(input.acknowledgedAt).toISOString() : null)

  const trigTime = input.triggeredTime
    ? new Date(input.triggeredTime).toISOString()
    : (input.deliveredAt ? new Date(input.deliveredAt).toISOString() : null)

  // Build clean reminder object adhering strictly to the schema with occurrence tracking
  const reminder = {
    id: input.id && typeof input.id === 'string' && input.id.trim()
      ? input.id.trim()
      : generateReminderId(),
    patientId: input.patientId.trim(),
    type: input.type,
    title: input.title.trim(),
    message: typeof input.message === 'string' ? input.message.trim() : '',
    scheduledTime: scheduledIso,
    repeat: input.repeat && isValidReminderRepeat(input.repeat) ? input.repeat : REMINDER_REPEAT.NONE,
    enabled: typeof input.enabled === 'boolean' ? input.enabled : true,
    voiceEnabled: typeof input.voiceEnabled === 'boolean' ? input.voiceEnabled : true,
    status: input.status && isValidReminderStatus(input.status) ? input.status : REMINDER_STATUS.UPCOMING,
    createdAt: input.createdAt ? new Date(input.createdAt).toISOString() : nowIso,

    // Occurrence tracking fields
    triggeredTime: trigTime,
    acknowledgedTime: ackTime,
    acknowledgedAt: ackTime,
    snoozed: typeof input.snoozed === 'boolean'
      ? input.snoozed
      : (input.status === REMINDER_STATUS.SNOOZED || Boolean(input.snoozedUntil)),
    attempts: typeof input.attempts === 'number' && Number.isFinite(input.attempts) && input.attempts >= 0
      ? Math.round(input.attempts)
      : (input.attemptCount || 0),
    snoozedUntil: input.snoozedUntil ? new Date(input.snoozedUntil).toISOString() : null,
  }

  return Object.freeze(reminder)
}

/**
 * ── Immutable Lifecycle State Transitions ───────────────────────────
 */

/**
 * Marks a reminder as acknowledged by the patient (or caregiver on their behalf).
 *
 * @param {Object} reminder
 * @param {string|Date} [timestamp]
 * @returns {Object} Next frozen reminder state
 */
export function acknowledgeReminder(reminder, timestamp = new Date()) {
  if (!reminder) return null
  const ackIso = (timestamp instanceof Date ? timestamp : new Date(timestamp)).toISOString()
  return Object.freeze({
    ...reminder,
    status: REMINDER_STATUS.ACKNOWLEDGED,
    acknowledgedTime: ackIso,
    acknowledgedAt: ackIso,
    snoozed: false,
    snoozedUntil: null,
  })
}

/**
 * Snoozes a reminder for a given duration (default 10 minutes).
 *
 * @param {Object} reminder
 * @param {number} [snoozeMinutes=10]
 * @param {Date} [fromTime=new Date()]
 * @returns {Object} Next frozen reminder state
 */
export function snoozeReminder(reminder, snoozeMinutes = 10, fromTime = new Date()) {
  if (!reminder) return null
  const snoozeDate = new Date(fromTime.getTime() + snoozeMinutes * 60 * 1000)
  return Object.freeze({
    ...reminder,
    status: REMINDER_STATUS.SNOOZED,
    snoozed: true,
    snoozedUntil: snoozeDate.toISOString(),
    acknowledgedTime: null,
    acknowledgedAt: null,
  })
}

/**
 * Marks a reminder as delivered/due on the patient's device.
 * Increments attempt count and records triggeredTime.
 *
 * @param {Object} reminder
 * @param {Date} [timestamp=new Date()]
 * @returns {Object} Next frozen reminder state
 */
export function markReminderDelivered(reminder, timestamp = new Date()) {
  if (!reminder) return null
  const trigIso = (timestamp instanceof Date ? timestamp : new Date(timestamp)).toISOString()
  return Object.freeze({
    ...reminder,
    status: REMINDER_STATUS.DUE,
    triggeredTime: trigIso,
    attempts: (reminder.attempts || 0) + 1,
  })
}

/**
 * Marks a reminder occurrence as Not Acknowledged when its alert window passes.
 *
 * POLICY NOTE:
 * Strictly uses "Not Acknowledged" instead of "Medication missed" because the
 * platform cannot conclude whether medicine was taken simply because the patient
 * did not interact with the device. Never makes clinical conclusions.
 *
 * @param {Object} reminder
 * @returns {Object} Next frozen reminder state
 */
export function markReminderNotAcknowledged(reminder) {
  if (!reminder) return null
  return Object.freeze({
    ...reminder,
    status: REMINDER_STATUS.NOT_ACKNOWLEDGED,
    snoozed: false,
  })
}

/** Backwards-compatible alias */
export const markReminderMissed = markReminderNotAcknowledged

/**
 * Dismisses a reminder without marking it acknowledged.
 *
 * @param {Object} reminder
 * @returns {Object} Next frozen reminder state
 */
export function dismissReminder(reminder) {
  if (!reminder) return null
  return Object.freeze({
    ...reminder,
    status: REMINDER_STATUS.NOT_ACKNOWLEDGED,
    snoozedUntil: null,
  })
}

/**
 * Toggles whether a reminder schedule is enabled or paused.
 *
 * @param {Object} reminder
 * @param {boolean} [enabled]
 * @returns {Object} Next frozen reminder state
 */
export function toggleReminderEnabled(reminder, enabled) {
  if (!reminder) return null
  const nextEnabled = typeof enabled === 'boolean' ? enabled : !reminder.enabled
  return Object.freeze({
    ...reminder,
    enabled: nextEnabled,
  })
}

/**
 * Produces an updated reminder with partial edits while preserving invariants.
 *
 * @param {Object} reminder
 * @param {Object} updates
 * @returns {Object} Next frozen reminder state
 */
export function updateReminder(reminder, updates) {
  if (!reminder) return null
  if (!updates || typeof updates !== 'object') return reminder

  // Filter out forbidden keys
  const safeUpdates = { ...updates }
  for (const forbidden of SENSITIVE_FORBIDDEN_KEYS) {
    delete safeUpdates[forbidden]
  }

  // Preserve core identifier and creation timestamp
  delete safeUpdates.id
  delete safeUpdates.createdAt

  const merged = {
    ...reminder,
    ...safeUpdates,
  }

  return createReminder(merged)
}

/**
 * ── Evaluation & Query Helpers ──────────────────────────────────────
 */

/**
 * Determines whether a reminder is currently due (scheduled time has passed
 * and reminder is enabled, pending or snoozed past snoozedUntil).
 *
 * @param {Object} reminder
 * @param {Date} [referenceTime=new Date()]
 * @returns {boolean}
 */
export function isReminderDue(reminder, referenceTime = new Date()) {
  if (!reminder || !reminder.enabled) return false

  const refMillis = referenceTime.getTime()
  const schedMillis = new Date(reminder.scheduledTime).getTime()

  if (reminder.status === REMINDER_STATUS.SNOOZED && reminder.snoozedUntil) {
    return refMillis >= new Date(reminder.snoozedUntil).getTime()
  }

  if (
    reminder.status === REMINDER_STATUS.UPCOMING ||
    reminder.status === REMINDER_STATUS.DUE ||
    reminder.status === 'pending' ||
    reminder.status === 'delivered'
  ) {
    return refMillis >= schedMillis
  }

  return false
}

/**
 * Determines if a reminder is scheduled for today relative to a reference date.
 *
 * @param {Object} reminder
 * @param {Date} [referenceDate=new Date()]
 * @returns {boolean}
 */
export function isReminderForDate(reminder, referenceDate = new Date()) {
  if (!reminder || !reminder.scheduledTime) return false

  const remDate = new Date(reminder.scheduledTime)
  return (
    remDate.getFullYear() === referenceDate.getFullYear() &&
    remDate.getMonth() === referenceDate.getMonth() &&
    remDate.getDate() === referenceDate.getDate()
  )
}
