// lib/core/models/patient_access_code.dart
//
// Model representing a unique, secure Patient Access Code generated by a Caregiver
// to allow an elderly patient to log in without email or password.

class PatientAccessCode {
  final String code; // Canonical format: SMR-XXXX-YY
  final String patientId;
  final String caregiverId;
  final String patientName;
  final String caregiverName;
  final DateTime createdAt;
  final DateTime expiresAt;
  final bool isActive;
  final bool isLinked;
  final DateTime? linkedAt;

  const PatientAccessCode({
    required this.code,
    required this.patientId,
    required this.caregiverId,
    required this.patientName,
    required this.caregiverName,
    required this.createdAt,
    required this.expiresAt,
    this.isActive = true,
    this.isLinked = false,
    this.linkedAt,
  });

  bool get isExpired => DateTime.now().isAfter(expiresAt);

  bool get isValid => isActive && !isExpired;

  /// Formatted presentation of the code (e.g. SMR-4827-KP)
  String get formattedCode => code;

  Map<String, dynamic> toMap() {
    return {
      'code': code,
      'patientId': patientId,
      'caregiverId': caregiverId,
      'patientName': patientName,
      'caregiverName': caregiverName,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt.toIso8601String(),
      'isActive': isActive,
      'isLinked': isLinked,
      'linkedAt': linkedAt?.toIso8601String(),
    };
  }

  factory PatientAccessCode.fromMap(Map<String, dynamic> map) {
    return PatientAccessCode(
      code: map['code'] as String? ?? '',
      patientId: map['patientId'] as String? ?? '',
      caregiverId: map['caregiverId'] as String? ?? '',
      patientName: map['patientName'] as String? ?? 'Patient',
      caregiverName: map['caregiverName'] as String? ?? 'Caregiver',
      createdAt: map['createdAt'] != null
          ? DateTime.tryParse(map['createdAt'] as String) ?? DateTime.now()
          : DateTime.now(),
      expiresAt: map['expiresAt'] != null
          ? DateTime.tryParse(map['expiresAt'] as String) ??
              DateTime.now().add(const Duration(days: 30))
          : DateTime.now().add(const Duration(days: 30)),
      isActive: map['isActive'] as bool? ?? true,
      isLinked: map['isLinked'] as bool? ?? false,
      linkedAt: map['linkedAt'] != null
          ? DateTime.tryParse(map['linkedAt'] as String)
          : null,
    );
  }

  PatientAccessCode copyWith({
    String? code,
    String? patientId,
    String? caregiverId,
    String? patientName,
    String? caregiverName,
    DateTime? createdAt,
    DateTime? expiresAt,
    bool? isActive,
    bool? isLinked,
    DateTime? linkedAt,
  }) {
    return PatientAccessCode(
      code: code ?? this.code,
      patientId: patientId ?? this.patientId,
      caregiverId: caregiverId ?? this.caregiverId,
      patientName: patientName ?? this.patientName,
      caregiverName: caregiverName ?? this.caregiverName,
      createdAt: createdAt ?? this.createdAt,
      expiresAt: expiresAt ?? this.expiresAt,
      isActive: isActive ?? this.isActive,
      isLinked: isLinked ?? this.isLinked,
      linkedAt: linkedAt ?? this.linkedAt,
    );
  }
}
